/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JogodosNumeros;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author luiza.bertti
 */
public class JogodosNumeros extends javax.swing.JFrame{

    /**
     * Creates new form JogodosNumeros
     */
    public CartaoAposta cart;
    public CartaoSorteio sorteio;
    private int contador;
    private Component[] botoes;
    private int totalBotoes;
    private int contadorAposta;
    
    public JogodosNumeros() {
        initComponents();
        totalBotoes = painelNumeros.getComponentCount();        
        botoes = new Component[totalBotoes];
        botoes = painelNumeros.getComponents();
        painelNumeros.setBackground(Color.green);
        contador=0;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbJogarNov = new javax.swing.JButton();
        jbVerificar = new javax.swing.JButton();
        painelNumeros = new javax.swing.JPanel();
        jtb1 = new javax.swing.JToggleButton();
        jtb2 = new javax.swing.JToggleButton();
        jtb3 = new javax.swing.JToggleButton();
        jtb4 = new javax.swing.JToggleButton();
        jtb5 = new javax.swing.JToggleButton();
        jtb6 = new javax.swing.JToggleButton();
        jtb7 = new javax.swing.JToggleButton();
        jtb8 = new javax.swing.JToggleButton();
        jtb9 = new javax.swing.JToggleButton();
        jtb10 = new javax.swing.JToggleButton();
        jtb30 = new javax.swing.JToggleButton();
        jtb29 = new javax.swing.JToggleButton();
        jtb28 = new javax.swing.JToggleButton();
        jtb27 = new javax.swing.JToggleButton();
        jtb26 = new javax.swing.JToggleButton();
        jtb25 = new javax.swing.JToggleButton();
        jtb24 = new javax.swing.JToggleButton();
        jtb23 = new javax.swing.JToggleButton();
        jtb22 = new javax.swing.JToggleButton();
        jtb21 = new javax.swing.JToggleButton();
        jtb40 = new javax.swing.JToggleButton();
        jtb39 = new javax.swing.JToggleButton();
        jtb38 = new javax.swing.JToggleButton();
        jtb37 = new javax.swing.JToggleButton();
        jtb36 = new javax.swing.JToggleButton();
        jtb35 = new javax.swing.JToggleButton();
        jtb34 = new javax.swing.JToggleButton();
        jtb33 = new javax.swing.JToggleButton();
        jtb32 = new javax.swing.JToggleButton();
        jtb31 = new javax.swing.JToggleButton();
        jtb50 = new javax.swing.JToggleButton();
        jtb49 = new javax.swing.JToggleButton();
        jtb48 = new javax.swing.JToggleButton();
        jtb47 = new javax.swing.JToggleButton();
        jtb46 = new javax.swing.JToggleButton();
        jtb45 = new javax.swing.JToggleButton();
        jtb44 = new javax.swing.JToggleButton();
        jtb43 = new javax.swing.JToggleButton();
        jtb42 = new javax.swing.JToggleButton();
        jtb41 = new javax.swing.JToggleButton();
        jtb20 = new javax.swing.JToggleButton();
        jtb19 = new javax.swing.JToggleButton();
        jtb18 = new javax.swing.JToggleButton();
        jtb17 = new javax.swing.JToggleButton();
        jtb16 = new javax.swing.JToggleButton();
        jtb15 = new javax.swing.JToggleButton();
        jtb14 = new javax.swing.JToggleButton();
        jtb13 = new javax.swing.JToggleButton();
        jtb12 = new javax.swing.JToggleButton();
        jtb11 = new javax.swing.JToggleButton();
        jcpResultado = new javax.swing.JScrollPane();
        jtaResultado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());

        jbJogarNov.setText("Jogar Novamente");
        jbJogarNov.setActionCommand("jbnJogarNov");
        jbJogarNov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJogarNovActionPerformed(evt);
            }
        });

        jbVerificar.setText("Verificar");
        jbVerificar.setActionCommand("jbnVerificar");
        jbVerificar.setEnabled(false);
        jbVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerificarActionPerformed(evt);
            }
        });

        painelNumeros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marque de 6 a 10 números", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Small", 3, 14))); // NOI18N
        painelNumeros.setToolTipText("");
        painelNumeros.setName(""); // NOI18N

        jtb1.setText("1");
        jtb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb2.setText("2");
        jtb2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb3.setText("3");
        jtb3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb4.setText("4");
        jtb4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb5.setText("5");
        jtb5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb6.setText("6");
        jtb6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb7.setText("7");
        jtb7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb8.setText("8");
        jtb8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb9.setText("9");
        jtb9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb10.setText("10");
        jtb10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb30.setText("30");
        jtb30.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb29.setText("29");
        jtb29.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb28.setText("28");
        jtb28.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb27.setText("27");
        jtb27.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb26.setText("26");
        jtb26.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb25.setText("25");
        jtb25.setToolTipText("");
        jtb25.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb24.setText("24");
        jtb24.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb23.setText("23");
        jtb23.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb22.setText("22");
        jtb22.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb21.setText("21");
        jtb21.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb40.setText("40");
        jtb40.setToolTipText("");
        jtb40.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb39.setText("39");
        jtb39.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb38.setText("38");
        jtb38.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb37.setText("37");
        jtb37.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb36.setText("36");
        jtb36.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb35.setText("35");
        jtb35.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb34.setText("34");
        jtb34.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb33.setText("33");
        jtb33.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb32.setText("32");
        jtb32.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb31.setText("31");
        jtb31.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb50.setText("50");
        jtb50.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb49.setText("49");
        jtb49.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb48.setText("48");
        jtb48.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb47.setText("47");
        jtb47.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb46.setText("46");
        jtb46.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb45.setText("45");
        jtb45.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb44.setText("44");
        jtb44.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb43.setText("43");
        jtb43.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb42.setText("42");
        jtb42.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb41.setText("41");
        jtb41.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb20.setText("20");
        jtb20.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb19.setText("19");
        jtb19.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb18.setText("18");
        jtb18.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb17.setText("17");
        jtb17.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb16.setText("16");
        jtb16.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb15.setText("15");
        jtb15.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb14.setText("14");
        jtb14.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb13.setText("13");
        jtb13.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb12.setText("12");
        jtb12.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        jtb11.setText("11");
        jtb11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoItemMudanca(evt);
            }
        });
        jtb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosSelecionados(evt);
            }
        });

        javax.swing.GroupLayout painelNumerosLayout = new javax.swing.GroupLayout(painelNumeros);
        painelNumeros.setLayout(painelNumerosLayout);
        painelNumerosLayout.setHorizontalGroup(
            painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelNumerosLayout.createSequentialGroup()
                        .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtb11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtb21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtb12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtb22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtb13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtb23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtb14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtb4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtb24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtb15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtb5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtb25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelNumerosLayout.createSequentialGroup()
                                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtb6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtb26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtb7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtb27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtb8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtb28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtb9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtb29, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtb10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtb30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(painelNumerosLayout.createSequentialGroup()
                                .addComponent(jtb16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtb17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtb18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtb19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtb20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelNumerosLayout.createSequentialGroup()
                        .addComponent(jtb31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb39, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelNumerosLayout.createSequentialGroup()
                        .addComponent(jtb41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb49, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelNumerosLayout.setVerticalGroup(
            painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb1)
                    .addComponent(jtb2)
                    .addComponent(jtb3)
                    .addComponent(jtb4)
                    .addComponent(jtb5)
                    .addComponent(jtb6)
                    .addComponent(jtb7)
                    .addComponent(jtb8)
                    .addComponent(jtb9)
                    .addComponent(jtb10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb11)
                    .addComponent(jtb12)
                    .addComponent(jtb13)
                    .addComponent(jtb14)
                    .addComponent(jtb15)
                    .addComponent(jtb16)
                    .addComponent(jtb17)
                    .addComponent(jtb18)
                    .addComponent(jtb19)
                    .addComponent(jtb20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb21)
                    .addComponent(jtb22)
                    .addComponent(jtb23)
                    .addComponent(jtb24)
                    .addComponent(jtb25)
                    .addComponent(jtb26)
                    .addComponent(jtb27)
                    .addComponent(jtb28)
                    .addComponent(jtb29)
                    .addComponent(jtb30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb31)
                    .addComponent(jtb32)
                    .addComponent(jtb33)
                    .addComponent(jtb34)
                    .addComponent(jtb35)
                    .addComponent(jtb36)
                    .addComponent(jtb37)
                    .addComponent(jtb38)
                    .addComponent(jtb39)
                    .addComponent(jtb40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb41)
                    .addComponent(jtb42)
                    .addComponent(jtb43)
                    .addComponent(jtb44)
                    .addComponent(jtb45)
                    .addComponent(jtb46)
                    .addComponent(jtb47)
                    .addComponent(jtb48)
                    .addComponent(jtb49)
                    .addComponent(jtb50))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtaResultado.setColumns(20);
        jtaResultado.setRows(5);
        jcpResultado.setViewportView(jtaResultado);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JogodosNumeros/Ibagens/jogodosnumeros.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcpResultado))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbJogarNov, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(painelNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcpResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jbVerificar)
                        .addGap(18, 18, 18)
                        .addComponent(jbJogarNov)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        painelNumeros.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jbVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerificarActionPerformed
       jbVerificar.setEnabled(false);
       cart = new CartaoAposta(contador);
       cart.numeroAposta += contadorAposta;
       pegarItensSelecionados();
       sorteio = new CartaoSorteio(6);
       jtaResultado.setText("Aposta numero: "+ cart.numeroAposta);
       jtaResultado.setText(jtaResultado.getText() + "\r\nNumeros Sorteados");
       jtaResultado.setText(jtaResultado.getText() + "\r\n" + sorteio.numerosCartao());
       jtaResultado.setText(jtaResultado.getText() + "\r\nValor da Aposta: " + cart.calculaAposta());
       jtaResultado.setText(jtaResultado.getText() + "\r\nTotal de acertos " + cart.totAcertos(sorteio));
       pintarJToggle();
       
    }//GEN-LAST:event_jbVerificarActionPerformed
    
    private void pintarJToggle(){
        JToggleButton verificarBotao;
        int i = 0;
        while(i<totalBotoes){
            if(botoes[i] instanceof JToggleButton){
                verificarBotao = (JToggleButton) botoes[i];
                if(verificarBotao.isSelected() && sorteio.existe(Integer.parseInt(verificarBotao.getActionCommand())) == false){
                    verificarBotao.setBackground(Color.MAGENTA);
                }                
            }
            i++;
        }
    }
    
    private void pegarItensSelecionados(){
        JToggleButton verificarBotao;
        int i = 0;
        while(i<totalBotoes){
            if(botoes[i] instanceof JToggleButton){
                verificarBotao = (JToggleButton) botoes[i];
                if(verificarBotao.isSelected()){
                    cart.addNumeros(Integer.parseInt(verificarBotao.getActionCommand()));       
                }  
            }
            i++;
        }
    }
    private void numerosSelecionados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosSelecionados
        // TODO add your handling code here:

    }//GEN-LAST:event_numerosSelecionados

    private void estadoItemMudanca(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_estadoItemMudanca
        // TODO add your handling code here:
        if(contador==10 && evt.getStateChange() != ItemEvent.DESELECTED){
            JOptionPane.showMessageDialog(this, "Você só pode selecionar 10 numeros no maximo");
            JToggleButton botao;
            botao = (JToggleButton) evt.getItem();
            botao.setSelected(false);
            return;
        }
        if(evt.getStateChange() == ItemEvent.SELECTED){
            contador++;
        }else if(evt.getStateChange() == ItemEvent.DESELECTED){
            contador--;
        }  
        if(contador == 6){
            jbVerificar.setEnabled(true);
        }
    }//GEN-LAST:event_estadoItemMudanca

    private void jbJogarNovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJogarNovActionPerformed
        // TODO add your handling code here:
        JToggleButton verificarBotao;
        int i = 0;
        while(i<totalBotoes){
            if(botoes[i] instanceof JToggleButton){
                verificarBotao = (JToggleButton) botoes[i];
                if(verificarBotao.isSelected()){
                    verificarBotao.setSelected(false);
                    if(verificarBotao.getBackground()==Color.MAGENTA){
                        verificarBotao.setBackground(Color.LIGHT_GRAY);
                    }
                }                
            }
            i++;
        }
        jtaResultado.setText("");
        contadorAposta = cart.numeroAposta;
        jbVerificar.setEnabled(false);
        contador = 0;
    }//GEN-LAST:event_jbJogarNovActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogodosNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JogodosNumeros().setVisible(true);
        });
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbJogarNov;
    private javax.swing.JButton jbVerificar;
    private javax.swing.JScrollPane jcpResultado;
    private javax.swing.JTextArea jtaResultado;
    private javax.swing.JToggleButton jtb1;
    private javax.swing.JToggleButton jtb10;
    private javax.swing.JToggleButton jtb11;
    private javax.swing.JToggleButton jtb12;
    private javax.swing.JToggleButton jtb13;
    private javax.swing.JToggleButton jtb14;
    private javax.swing.JToggleButton jtb15;
    private javax.swing.JToggleButton jtb16;
    private javax.swing.JToggleButton jtb17;
    private javax.swing.JToggleButton jtb18;
    private javax.swing.JToggleButton jtb19;
    private javax.swing.JToggleButton jtb2;
    private javax.swing.JToggleButton jtb20;
    private javax.swing.JToggleButton jtb21;
    private javax.swing.JToggleButton jtb22;
    private javax.swing.JToggleButton jtb23;
    private javax.swing.JToggleButton jtb24;
    private javax.swing.JToggleButton jtb25;
    private javax.swing.JToggleButton jtb26;
    private javax.swing.JToggleButton jtb27;
    private javax.swing.JToggleButton jtb28;
    private javax.swing.JToggleButton jtb29;
    private javax.swing.JToggleButton jtb3;
    private javax.swing.JToggleButton jtb30;
    private javax.swing.JToggleButton jtb31;
    private javax.swing.JToggleButton jtb32;
    private javax.swing.JToggleButton jtb33;
    private javax.swing.JToggleButton jtb34;
    private javax.swing.JToggleButton jtb35;
    private javax.swing.JToggleButton jtb36;
    private javax.swing.JToggleButton jtb37;
    private javax.swing.JToggleButton jtb38;
    private javax.swing.JToggleButton jtb39;
    private javax.swing.JToggleButton jtb4;
    private javax.swing.JToggleButton jtb40;
    private javax.swing.JToggleButton jtb41;
    private javax.swing.JToggleButton jtb42;
    private javax.swing.JToggleButton jtb43;
    private javax.swing.JToggleButton jtb44;
    private javax.swing.JToggleButton jtb45;
    private javax.swing.JToggleButton jtb46;
    private javax.swing.JToggleButton jtb47;
    private javax.swing.JToggleButton jtb48;
    private javax.swing.JToggleButton jtb49;
    private javax.swing.JToggleButton jtb5;
    private javax.swing.JToggleButton jtb50;
    private javax.swing.JToggleButton jtb6;
    private javax.swing.JToggleButton jtb7;
    private javax.swing.JToggleButton jtb8;
    private javax.swing.JToggleButton jtb9;
    private javax.swing.JPanel painelNumeros;
    // End of variables declaration//GEN-END:variables
}
